### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pet239617** [spazbg/uchase#5]
When I open uchase.exe appears this:

Starting ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}) on port 50153
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

Unhandled Exception: OpenQA.Selenium.WebDriverException: unknown error: cannot find Chrome binary
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at uchase.Program.Main(String[] args) in C:\Users\Sp4z\source\repos\uchase\Program.cs:line 22

What to do?

**Comment by abdh-dev** [comment]
idk if bro still needs help but you need to download the chrome driver binary and put in the project directory (i think? or where the program is looking for it)

https://googlechromelabs.github.io/chrome-for-testing/
